name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # 🌈 Display options
          SHOW_TITLE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_TIMEZONE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_OS: "True"
          SHOW_WEEK_STATS: "True"
          
          # 🎨 Style customization
          BLOCKS: "⬜🟨🟧🟥"
          COMMIT_MESSAGE: "⚡️ Update WakaTime stats in README"
          TIME_RANGE: "all_time"
          LOCALE: "en"
          DEBUG_LOGGING: "False"
